services:
  db:
    image: postgres:16
    container_name: docbook_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-docbookdb}
      POSTGRES_USER: ${POSTGRES_USER:-docbookuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docbookpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-docbookuser} -d ${POSTGRES_DB:-docbookdb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: docbook_web
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8080"

volumes:
  pgdata: {}
